import { createContext, useContext, useState, useEffect } from 'react';

const STORAGE_KEY = 'zikaron_lang';

const translations = {
  he: {
    'app.name': 'בשביל הזיכרון 7 באוקטובר',

    'nav.home': 'בית',
    'nav.map': 'מפה',
    'nav.search': 'חיפוש',
    'nav.route': 'מסלול',
    'nav.admin': 'ניהול',
    'nav.login': 'כניסה',

    'footer.desc': 'תיעוד מה שקרה ב-7 באוקטובר 2023 — מקום אחד, סיפור אחד. לכל מי שעומד באחד מהמקומות בעוטף עזה ורוצה להבין.',
    'footer.quickLinks': 'קישורים מהירים',
    'footer.contactLegal': 'יצירת קשר ומידע משפטי',
    'footer.contact': 'יצירת קשר',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
    'footer.accessibility': 'הצהרת נגישות',
    'footer.about': 'אודות',
    'footer.memorial': 'לזכרם של כל מי שנרצח, נחטף ונפל — ב-7 באוקטובר 2023 ובמלחמת חרבות ברזל',
    'footer.mapOfSites': 'מפת המקומות',
    'footer.recommendedRoute': 'מסלול מומלץ',
    'footer.searchLocations': 'חיפוש מקומות',

    'location.loading': 'טוען את פרטי המקום...',
    'location.errorTitle': 'שגיאה בטעינת המקום',
    'location.notFound': 'המקום לא נמצא',
    'location.tryAgain': 'נסה שוב',
    'location.back': 'חזור',
    'location.share': 'שתף',
    'location.listen': 'שמע מה קרה כאן',
    'location.pressToListen': 'לחץ להאזנה לסיפור המקום ב-7 באוקטובר',
    'location.photos': 'תמונות מהמקום',
    'location.videos': 'קטעי וידאו',
    'location.navigate': 'נווט למקום',
    'location.navigationOpens': 'יפתח את אפליקציית הניווט במכשיר שלך',
    'location.readMore': 'המשך לקרוא',
    'location.readLess': 'הסתר טקסט',
    'location.linkCopied': 'הקישור הועתק ללוח',
    'location.defaultStory': 'מקום שבו התרחשו אירועי 7 באוקטובר 2023 — הסיפור המלא יתווסף בקרוב',
    'location.networkError': 'בעיית רשת או שרת עמוס. נסה שוב בעוד מספר שניות.',
    'location.loadError': 'שגיאה בטעינת המידע: ',
    'location.recordingPending': 'הסיפור בהכנה',
    'location.recordingPendingDesc': 'סיפור המקום יתווסף בקרוב',
    'location.shareAudio': 'שתף הקלטה',
    'location.nextStopHeader': 'מקום נוסף לשמוע',
    'location.nextStopLabel': 'המקום הבא:',
    'location.nextStopBtn': 'לסיפור הבא',
    'location.navigateNext': 'נווט',

    'home.title': 'כאן זה קרה — זיכרון 7 באוקטובר',
    'home.subtitle': 'עמדת במקום שבו קרה משהו שהוא לא יכול להישאר בלתי מובן. כאן תוכל לשמוע בדיוק מה התרחש ב-7 באוקטובר — מה שקרה בתחילת אותו בוקר, איך התפתחו האירועים, ומה נשאר אחרי.',
    'home.openMap': 'מפת המקומות',
    'home.startRoute': 'מקומות נוספים',
    'home.howItWorks': 'איך זה עובד?',
    'home.step1Title': 'הגע למקום',
    'home.step1Desc': 'הגע לאחד מהאתרים בעוטף עזה',
    'home.step2Title': 'סרוק את הקוד',
    'home.step2Desc': 'סרוק את קוד ה-QR שמוצב באתר',
    'home.step3Title': 'הבן מה קרה כאן',
    'home.step3Desc': 'שמע את הסיפור המלא של המקום — מה שהתרחש בו ב-7 באוקטובר',
    'home.memorialRouteTitle': 'מסלול הזיכרון',
    'home.memorialRouteDesc': 'ביקרת באתר אחד ורוצה לשמוע עוד? המסלול מחבר בין האתרים המרכזיים בעוטף עזה — כל תחנה מספרת את הסיפור של המקום הזה ב-7 באוקטובר.',
    'home.duration': 'משך משוער: כ-4 שעות',
    'home.routePoints': 'נקודות',
    'home.showOnMap': 'הצג מסלול במפה',
    'home.routeStops': 'נקודות במסלול:',
    'home.andMore': 'ועוד...',
    'home.nearbyTitle': 'מקומות קרובים אליך',
    'home.recommendedTitle': 'מקומות מומלצים',
    'home.nearbySubtitle': 'התחל את המסע שלך מאחד המקומות הבאים',
    'home.openStory': 'פתח סיפור המקום',
    'home.viewAll': 'צפה בכל המקומות',
    'home.defaultStory': 'מקום שבו התרחשו אירועי 7 באוקטובר 2023 — הסיפור המלא יתווסף בקרוב',

    'search.title': 'חיפוש מקומות',
    'search.subtitle': 'חפש מקום ספציפי בעוטף עזה ושמע מה קרה שם ב-7 באוקטובר 2023',
    'search.placeholder': 'חפש לפי שם מקום, תיאור או מילות מפתח...',
    'search.filter': 'סינון:',
    'search.sort': 'מיון:',
    'search.allTypes': 'כל הסוגים',
    'search.townPlural': 'יישובים',
    'search.militaryPlural': 'בסיסי צבא',
    'search.eventPlural': 'אירועים',
    'search.otherPlural': 'מקומות אחרים',
    'search.shelterPlural': 'מיגוניות',
    'search.sortName': 'שם המקום',
    'search.sortViews': 'מספר צפיות',
    'search.sortRecent': 'הוספה אחרונה',
    'search.loading': 'טוען...',
    'search.foundMany': 'נמצאו {count} מקומות',
    'search.foundOne': 'מקום אחד נמצא',
    'search.resultsFor': 'תוצאות חיפוש עבור:',
    'search.noResults': 'לא נמצאו תוצאות',
    'search.noResultsHint': 'נסה לשנות את מונחי החיפוש או הסר חלק מהסינונים',
    'search.clearSearch': 'נקה חיפוש',
    'search.discoverMore': 'גלה עוד',
    'search.showOnMap': 'מפה',
    'search.audio': 'הקלטה',
    'search.errorTitle': 'שגיאה בטעינת המידע',
    'search.cannotLoad': 'לא ניתן לטעון את המידע',
    'search.tryLater': 'אירעה שגיאה בטעינת רשימת המקומות. אנא נסה שוב מאוחר יותר.',
    'search.tryAgain': 'נסה שוב',
    'search.retrying': 'מנסה שוב... ניסיון {n}/2',

    'route.title': 'מקומות נוספים לביקור',
    'route.stops': 'תחנות',
    'route.duration': 'משך משוער:',
    'route.hours': 'שעות',
    'route.totalDistance': 'מרחק כולל:',
    'route.km': 'ק"מ',
    'route.startNavigation': 'התחל ניווט',
    'route.navigateTo': 'נווט למקום',
    'route.moreInfo': 'למידע נוסף',
    'route.recommendedTime': 'זמן מומלץ באתר:',
    'route.minutes': 'דקות',
    'route.prevDistance': 'מרחק מהתחנה הקודמת:',
    'route.driveTime': 'זמן נסיעה:',
    'route.defaultStory': 'אתר זיכרון משמעותי מאירועי 7 באוקטובר 2023',
    'route.mapTitle': 'מפת המסלול',
    'route.mapLocations': 'מפת המקומות',
    'route.clickForInfo': 'לחצו על התחנות במפה לקבלת מידע נוסף',
    'route.stopsTitle': 'תחנות המסלול',
    'route.stop': 'תחנה',
    'route.importantNotes': 'הערות חשובות למטיילים',
    'route.shareLocationBtn': 'שתף מיקום',
    'route.adjustToMyLocation': 'התאם למיקום שלי',
    'route.startRouteBtn': 'התחל את המסלול',
    'route.viewMap': 'צפה במפה',
    'route.inGazaEnvelope': 'אתם באזור עוטף עזה — הנה המקומות הקרובים אליכם לפי סדר הגיוני.',
    'route.fromSderot': 'המסלול מתחיל משדרות ומוביל בין המקומות המרכזיים לפי סדר הגיוני.',
    'route.loadingLocations': 'טוען מקומות...',
    'route.locatingPosition': 'מאתר מיקום...',
    'route.locating': 'מאתר...',
    'route.shareYourLocation': 'שתף את המיקום שלך',
    'route.shareLocationDesc': 'שתף את מיקומך כדי לראות את המקומות הקרובים אליך',
    'route.orStartFromSderot': 'או שנתחיל עם מסלול כללי משדרות',
    'route.mapSubtitleRoute': 'לחצו על התחנות במפה לקבלת מידע נוסף',
    'route.mapSubtitleSderot': 'המסלול מתחיל בשדרות ומותאם לסדר מסלול הגיוני',
    'route.mapSubtitleShare': 'שתפו את המיקום שלכם כדי לקבל מסלול מותאם אישית',
    'route.markVisited': 'סמן כביקרתי',
    'route.visited': 'ביקרתי',
    'route.mode.label': 'בחר מסלול:',
    'route.mode.essential': 'קצר',
    'route.mode.essentialDesc': 'תחנות חובה בלבד',
    'route.mode.recommended': 'מומלץ',
    'route.mode.recommendedDesc': 'תחנות עיקריות',
    'route.mode.full': 'מלא',
    'route.mode.fullDesc': 'כל התחנות',
    'route.mode.custom': 'לפי זמן',
    'route.mode.budgetLabel': 'תקציב זמן:',
    'route.mode.hours': 'שעות',
    'route.mode.noPriorityHint': 'טיפ: סמן מקומות כ"חובה" בניהול כדי לאפשר מסלול קצר',
    'route.customizeHint': 'ניתן להסיר כל תחנה עם ✕ ולהוסיף מקומות נוספים — המסלול יסתגל אוטומטית',
    'route.notInRoute': 'מקומות שלא במסלול',
    'route.notInRouteHint': 'לחץ על "הוסף" כדי לשלב מקום נוסף; המסלול יחושב מחדש אוטומטית',
    'route.addToRoute': 'הוסף',
    'route.resetRoute': 'שחזר מסלול',

    'priority.essential': 'חובה — תחנה מרכזית',
    'priority.recommended': 'מומלץ — תחנה רגילה',
    'priority.extended': 'מורחב — תחנה בונוס',

    'route.note.hoursLabel': 'שעות פעילות:',
    'route.note.hours': 'מומלץ לבקר בשעות היום בלבד (06:00–18:00)',
    'route.note.securityLabel': 'ביטחון:',
    'route.note.security': 'יש להישאר בשטחים המותרים ולציית להנחיות הביטחון המקומיות',
    'route.note.waterLabel': 'מים ושירותים:',
    'route.note.water': 'מומלץ להביא מים ולתכנן הפסקות בישובים עם שירותים',
    'route.note.emergencyLabel': 'טלפון חירום:',
    'route.note.emergency': '100 משטרה, 101 מד"א, 102 כיבוי אש',
    'route.note.weatherLabel': 'מזג אוויר:',
    'route.note.weather': 'בדקו תחזית מזג האוויר לפני היציאה',

    'category.יישוב': 'יישוב',
    'category.אירוע': 'אירוע',
    'category.מקום אחר': 'מקום אחר',
    'category.מיגונית': 'מיגונית',
  },

  en: {
    'app.name': 'In Memory of October 7',

    'nav.home': 'Home',
    'nav.map': 'Map',
    'nav.search': 'Search',
    'nav.route': 'Route',
    'nav.admin': 'Admin',
    'nav.login': 'Login',

    'footer.desc': 'Documenting what happened on October 7, 2023 — one place, one story. For anyone standing at one of the sites in the Gaza Envelope who wants to understand.',
    'footer.quickLinks': 'Quick Links',
    'footer.contactLegal': 'Contact & Legal',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.accessibility': 'Accessibility Statement',
    'footer.about': 'About',
    'footer.memorial': 'In memory of all those murdered, abducted, and fallen — on October 7, 2023 and throughout the Iron Swords War',
    'footer.mapOfSites': 'Sites Map',
    'footer.recommendedRoute': 'Recommended Route',
    'footer.searchLocations': 'Search Locations',

    'location.loading': 'Loading location...',
    'location.errorTitle': 'Error Loading Location',
    'location.notFound': 'Location not found',
    'location.tryAgain': 'Try Again',
    'location.back': 'Back',
    'location.share': 'Share',
    'location.listen': 'Hear What Happened Here',
    'location.pressToListen': 'Press to listen to the story of this place on October 7',
    'location.photos': 'Photos',
    'location.videos': 'Video Clips',
    'location.navigate': 'Navigate to Location',
    'location.navigationOpens': 'Will open your navigation app',
    'location.readMore': 'Read more',
    'location.readLess': 'Show less',
    'location.linkCopied': 'Link copied to clipboard',
    'location.defaultStory': 'A location where the events of October 7, 2023 took place — the full story will be added soon',
    'location.networkError': 'Network error or server busy. Please try again in a few seconds.',
    'location.loadError': 'Error loading data: ',
    'location.recordingPending': 'Story Coming Soon',
    'location.recordingPendingDesc': 'The story of this location will be added soon',
    'location.shareAudio': 'Share Recording',
    'location.nextStopHeader': 'Another Place to Hear',
    'location.nextStopLabel': 'Next Location:',
    'location.nextStopBtn': 'Next Story',
    'location.navigateNext': 'Navigate',

    'home.title': 'This Is Where It Happened — October 7 Memorial',
    'home.subtitle': 'You are standing at a place where something happened that cannot remain unexplained. Here you can hear exactly what unfolded on October 7 — what began that morning, how events developed, and what remained after.',
    'home.openMap': 'Map of Sites',
    'home.startRoute': 'More Locations',
    'home.howItWorks': 'How Does It Work?',
    'home.step1Title': 'Arrive at the site',
    'home.step1Desc': 'Visit one of the sites in the Gaza Envelope',
    'home.step2Title': 'Scan the code',
    'home.step2Desc': 'Scan the QR code placed at the site',
    'home.step3Title': 'Understand what happened here',
    'home.step3Desc': 'Hear the full story of the place — what unfolded there on October 7',
    'home.memorialRouteTitle': 'The Memorial Route',
    'home.memorialRouteDesc': 'Visited one site and want to hear more? The route connects the main sites across the Gaza Envelope — each stop tells the story of what happened at that place on October 7.',
    'home.duration': 'Estimated duration: ~4 hours',
    'home.routePoints': 'stops',
    'home.showOnMap': 'Show Route on Map',
    'home.routeStops': 'Route stops:',
    'home.andMore': 'and more...',
    'home.nearbyTitle': 'Locations Near You',
    'home.recommendedTitle': 'Recommended Locations',
    'home.nearbySubtitle': 'Start your journey from one of these locations',
    'home.openStory': 'Open Location Story',
    'home.viewAll': 'View All Locations',
    'home.defaultStory': 'A location where the events of October 7, 2023 took place — the full story will be added soon',

    'search.title': 'Search Locations',
    'search.subtitle': 'Search for a specific location in the Gaza Envelope and hear what happened there on October 7, 2023',
    'search.placeholder': 'Search by location name, description or keywords...',
    'search.filter': 'Filter:',
    'search.sort': 'Sort by:',
    'search.allTypes': 'All Types',
    'search.townPlural': 'Towns',
    'search.militaryPlural': 'Military Bases',
    'search.eventPlural': 'Event Sites',
    'search.otherPlural': 'Other Locations',
    'search.shelterPlural': 'Bomb Shelters',
    'search.sortName': 'Location Name',
    'search.sortViews': 'Most Viewed',
    'search.sortRecent': 'Recently Added',
    'search.loading': 'Loading...',
    'search.foundMany': '{count} locations found',
    'search.foundOne': '1 location found',
    'search.resultsFor': 'Search results for:',
    'search.noResults': 'No results found',
    'search.noResultsHint': 'Try different search terms or remove some filters',
    'search.clearSearch': 'Clear Search',
    'search.discoverMore': 'Discover More',
    'search.showOnMap': 'Map',
    'search.audio': 'Audio',
    'search.errorTitle': 'Error Loading Data',
    'search.cannotLoad': 'Unable to load data',
    'search.tryLater': 'An error occurred loading the locations list. Please try again later.',
    'search.tryAgain': 'Try Again',
    'search.retrying': 'Retrying... attempt {n}/2',

    'route.title': 'More Locations to Visit',
    'route.stops': 'stops',
    'route.duration': 'Est. duration:',
    'route.hours': 'hours',
    'route.totalDistance': 'Total distance:',
    'route.km': 'km',
    'route.startNavigation': 'Start Navigation',
    'route.navigateTo': 'Navigate',
    'route.moreInfo': 'More Info',
    'route.recommendedTime': 'Recommended time:',
    'route.minutes': 'min',
    'route.prevDistance': 'Distance from previous stop:',
    'route.driveTime': 'Drive time:',
    'route.defaultStory': 'A significant memorial site from the October 7, 2023 events',
    'route.mapTitle': 'Route Map',
    'route.mapLocations': 'Locations Map',
    'route.clickForInfo': 'Click on stops for more information',
    'route.stopsTitle': 'Route Stops',
    'route.stop': 'Stop',
    'route.importantNotes': 'Important Notes for Visitors',
    'route.shareLocationBtn': 'Share Location',
    'route.adjustToMyLocation': 'Adjust to My Location',
    'route.startRouteBtn': 'Start Route',
    'route.viewMap': 'View Map',
    'route.inGazaEnvelope': 'You are in the Gaza Envelope — here are the nearby locations in a logical order.',
    'route.fromSderot': 'The route starts from Sderot and leads through the main locations in a logical order.',
    'route.loadingLocations': 'Loading locations...',
    'route.locatingPosition': 'Locating...',
    'route.locating': 'Locating...',
    'route.shareYourLocation': 'Share Your Location',
    'route.shareLocationDesc': 'Share your location to see the locations closest to you',
    'route.orStartFromSderot': 'Or start with a general route from Sderot',
    'route.mapSubtitleRoute': 'Click on stops for more information',
    'route.mapSubtitleSderot': 'Route starts from Sderot in a logical visiting order',
    'route.mapSubtitleShare': 'Share your location to get a personalized route',
    'route.markVisited': 'Mark as Visited',
    'route.visited': 'Visited',
    'route.mode.label': 'Choose route:',
    'route.mode.essential': 'Short',
    'route.mode.essentialDesc': 'Must-see stops only',
    'route.mode.recommended': 'Recommended',
    'route.mode.recommendedDesc': 'Main stops',
    'route.mode.full': 'Full',
    'route.mode.fullDesc': 'All stops',
    'route.mode.custom': 'By Time',
    'route.mode.budgetLabel': 'Time budget:',
    'route.mode.hours': 'hours',
    'route.mode.noPriorityHint': 'Tip: Mark locations as "essential" in admin to enable short routes',
    'route.customizeHint': 'You can remove any stop with ✕ and add more locations — the route adjusts automatically',
    'route.notInRoute': 'Locations not in route',
    'route.notInRouteHint': 'Click "Add" to include a location; the route will recalculate automatically',
    'route.addToRoute': 'Add',
    'route.resetRoute': 'Reset route',

    'priority.essential': 'Essential — main stop',
    'priority.recommended': 'Recommended — regular stop',
    'priority.extended': 'Extended — bonus stop',

    'route.note.hoursLabel': 'Hours:',
    'route.note.hours': 'Recommended visiting hours are daytime only (06:00–18:00)',
    'route.note.securityLabel': 'Security:',
    'route.note.security': 'Stay in permitted areas and follow local security instructions',
    'route.note.waterLabel': 'Water & Facilities:',
    'route.note.water': 'Bring water and plan breaks at locations with facilities',
    'route.note.emergencyLabel': 'Emergency Numbers:',
    'route.note.emergency': '100 Police, 101 Ambulance, 102 Fire Department',
    'route.note.weatherLabel': 'Weather:',
    'route.note.weather': 'Check the weather forecast before your visit',

    'category.יישוב': 'Town',
    'category.אירוע': 'Event Site',
    'category.מקום אחר': 'Other Site',
    'category.מיגונית': 'Bomb Shelter',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === 'en' ? 'en' : 'he';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => translations[lang]?.[key] ?? translations.he[key] ?? key;
  const toggleLang = () => setLang(l => (l === 'he' ? 'en' : 'he'));
  const isRTL = lang === 'he';

  // Resolve display name/story for a location object based on current language
  const locName = (loc) => (lang === 'en' && loc?.name_en) ? loc.name_en : loc?.name;
  const locStoryTitle = (loc) => (lang === 'en' && loc?.full_story_en?.title) ? loc.full_story_en.title : loc?.full_story?.title;
  const locStoryContent = (loc) => (lang === 'en' && loc?.full_story_en?.content) ? loc.full_story_en.content : loc?.full_story?.content;

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, isRTL, locName, locStoryTitle, locStoryContent }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
