import { createContext, useContext, useState, useEffect } from 'react';

const STORAGE_KEY = 'zikaron_lang';

const translations = {
  he: {
    'app.name': 'זיכרון 7.10',

    'nav.home': 'בית',
    'nav.map': 'מפה',
    'nav.search': 'חיפוש',
    'nav.route': 'מסלול',
    'nav.admin': 'ניהול',
    'nav.login': 'כניסה',

    'footer.desc': 'אפליקציה המתעדת ומנציחה את אתרי הזיכרון מאירועי 7 באוקטובר 2023, ומאפשרת למשתמשים לחוות את הסיפורים דרך מסלולי טיול מודרכים.',
    'footer.quickLinks': 'קישורים מהירים',
    'footer.contactLegal': 'יצירת קשר ומידע משפטי',
    'footer.contact': 'יצירת קשר',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
    'footer.about': 'אודות',
    'footer.memorial': 'לזכר חללי ונספי 7 באוקטובר 2023',
    'footer.mapOfSites': 'מפת האתרים',
    'footer.recommendedRoute': 'מסלול מומלץ',
    'footer.searchLocations': 'חיפוש מקומות',

    'location.loading': 'טוען את פרטי המקום...',
    'location.errorTitle': 'שגיאה בטעינת המקום',
    'location.notFound': 'המקום לא נמצא',
    'location.tryAgain': 'נסה שוב',
    'location.back': 'חזור',
    'location.share': 'שתף',
    'location.listen': 'האזן לסיפור המקום',
    'location.pressToListen': 'לחץ על הכפתור כדי להתחיל האזנה',
    'location.photos': 'תמונות מהמקום',
    'location.videos': 'קטעי וידאו',
    'location.navigate': 'נווט למקום',
    'location.navigationOpens': 'יפתח את אפליקציית הניווט במכשיר שלך',
    'location.readMore': 'המשך לקרוא',
    'location.readLess': 'הסתר טקסט',
    'location.linkCopied': 'הקישור הועתק ללוח',
    'location.defaultStory': 'מקום זיכרון משמעותי מאירועי 7 באוקטובר',
    'location.networkError': 'בעיית רשת או שרת עמוס. נסה שוב בעוד מספר שניות.',
    'location.loadError': 'שגיאה בטעינת המידע: ',
    'location.recordingPending': 'הקלטה בהכנה',
    'location.recordingPendingDesc': 'הקלטת הסיפור של מקום זה תתווסף בקרוב',
    'location.shareAudio': 'שתף הקלטה',
    'location.nextStopHeader': 'המשך המסלול',
    'location.nextStopLabel': 'התחנה הבאה:',
    'location.nextStopBtn': 'לתחנה הבאה',
    'location.navigateNext': 'נווט',

    'home.title': 'צועדים בשביל הזיכרון',
    'home.subtitle': 'אפליקציה זו מלווה אותך במסע בין אתרי הטבח בעוטף עזה, ומספרת את סיפורם של המקומות באותו יום נורא – 7 באוקטובר 2023.',
    'home.openMap': 'פתח את המפה',
    'home.startRoute': 'התחל מסלול מומלץ',
    'home.howItWorks': 'איך זה עובד?',
    'home.step1Title': 'נווט אל אתר',
    'home.step1Desc': 'בחר מקום במפה או במסלול המומלץ',
    'home.step2Title': 'סרוק את הקוד במקום',
    'home.step2Desc': 'כדי לוודא שאתה בנקודה המדויקת',
    'home.step3Title': 'האזן לסיפור',
    'home.step3Desc': 'בליווי תמונות וקטעי וידאו',
    'home.memorialRouteTitle': 'מסלול הזיכרון',
    'home.memorialRouteDesc': 'צא למסע בעקבות אתרי הזיכרון המרכזיים ברצועת עזה. המסלול המומלץ יוביל אותך דרך הנקודות המשמעותיות ביותר באירועי 7 באוקטובר.',
    'home.duration': 'משך משוער: כ-4 שעות',
    'home.routePoints': 'נקודות',
    'home.showOnMap': 'הצג מסלול במפה',
    'home.routeStops': 'נקודות במסלול:',
    'home.andMore': 'ועוד...',
    'home.nearbyTitle': 'מקומות קרובים אליך',
    'home.recommendedTitle': 'מקומות מומלצים',
    'home.nearbySubtitle': 'התחל את המסע שלך מאחד המקומות הבאים',
    'home.openStory': 'פתח סיפור המקום',
    'home.viewAll': 'צפה בכל המקומות',
    'home.defaultStory': 'מקום זיכרון משמעותי מאירועי 7 באוקטובר',

    'search.title': 'חיפוש מקומות',
    'search.subtitle': 'חפש ומצא מידע על המקומות שנפגעו ביום 7 באוקטובר 2023',
    'search.placeholder': 'חפש לפי שם מקום, תיאור או מילות מפתח...',
    'search.filter': 'סינון:',
    'search.sort': 'מיון:',
    'search.allTypes': 'כל הסוגים',
    'search.townPlural': 'יישובים',
    'search.militaryPlural': 'בסיסי צבא',
    'search.eventPlural': 'אירועים',
    'search.otherPlural': 'מקומות אחרים',
    'search.shelterPlural': 'מיגוניות',
    'search.sortName': 'שם המקום',
    'search.sortViews': 'מספר צפיות',
    'search.sortRecent': 'הוספה אחרונה',
    'search.loading': 'טוען...',
    'search.foundMany': 'נמצאו {count} מקומות',
    'search.foundOne': 'מקום אחד נמצא',
    'search.resultsFor': 'תוצאות חיפוש עבור:',
    'search.noResults': 'לא נמצאו תוצאות',
    'search.noResultsHint': 'נסה לשנות את מונחי החיפוש או הסר חלק מהסינונים',
    'search.clearSearch': 'נקה חיפוש',
    'search.discoverMore': 'גלה עוד',
    'search.showOnMap': 'מפה',
    'search.audio': 'הקלטה',
    'search.errorTitle': 'שגיאה בטעינת המידע',
    'search.cannotLoad': 'לא ניתן לטעון את המידע',
    'search.tryLater': 'אירעה שגיאה בטעינת רשימת המקומות. אנא נסה שוב מאוחר יותר.',
    'search.tryAgain': 'נסה שוב',
    'search.retrying': 'מנסה שוב... ניסיון {n}/2',

    'route.title': 'מסלול מומלץ',
    'route.stops': 'תחנות',
    'route.duration': 'משך משוער:',
    'route.hours': 'שעות',
    'route.totalDistance': 'מרחק כולל:',
    'route.km': 'ק"מ',
    'route.startNavigation': 'התחל ניווט',
    'route.navigateTo': 'נווט למקום',
    'route.moreInfo': 'למידע נוסף',
    'route.recommendedTime': 'זמן מומלץ באתר:',
    'route.minutes': 'דקות',
    'route.prevDistance': 'מרחק מהתחנה הקודמת:',
    'route.driveTime': 'זמן נסיעה:',
    'route.defaultStory': 'אתר זיכרון משמעותי מאירועי 7 באוקטובר 2023',
    'route.mapTitle': 'מפת המסלול',
    'route.mapLocations': 'מפת המקומות',
    'route.clickForInfo': 'לחצו על התחנות במפה לקבלת מידע נוסף',
    'route.stopsTitle': 'תחנות המסלול',
    'route.stop': 'תחנה',
    'route.importantNotes': 'הערות חשובות למטיילים',
    'route.shareLocationBtn': 'שתף מיקום',
    'route.adjustToMyLocation': 'התאם למיקום שלי',
    'route.startRouteBtn': 'התחל את המסלול',
    'route.viewMap': 'צפה במפה',
    'route.inGazaEnvelope': 'זוהה שאתם נמצאים באזור עוטף עזה. המסלול מותאם למיקום שלכם.',
    'route.fromSderot': 'המסלול נבנה בצורה אופטימלית החל משדרות עם סדר ביקור הגיוני בין האתרים.',
    'route.loadingLocations': 'טוען מקומות...',
    'route.locatingPosition': 'מאתר מיקום...',
    'route.locating': 'מאתר...',
    'route.shareYourLocation': 'שתף את המיקום שלך',
    'route.shareLocationDesc': 'כדי ליצור מסלול מותאם אישית, נצטרך לגשת למיקום שלך ולהציג את המסלול הטוב ביותר עבורך',
    'route.orStartFromSderot': 'או שנתחיל עם מסלול כללי משדרות',
    'route.mapSubtitleRoute': 'לחצו על התחנות במפה לקבלת מידע נוסף',
    'route.mapSubtitleSderot': 'המסלול מתחיל בשדרות ומותאם לסדר מסלול הגיוני',
    'route.mapSubtitleShare': 'שתפו את המיקום שלכם כדי לקבל מסלול מותאם אישית',
    'route.markVisited': 'סמן כביקרתי',
    'route.visited': 'ביקרתי',
    'route.mode.label': 'בחר מסלול:',
    'route.mode.essential': 'קצר',
    'route.mode.essentialDesc': 'תחנות חובה בלבד',
    'route.mode.recommended': 'מומלץ',
    'route.mode.recommendedDesc': 'תחנות עיקריות',
    'route.mode.full': 'מלא',
    'route.mode.fullDesc': 'כל התחנות',
    'route.mode.custom': 'לפי זמן',
    'route.mode.budgetLabel': 'תקציב זמן:',
    'route.mode.hours': 'שעות',
    'route.mode.noPriorityHint': 'טיפ: סמן מקומות כ"חובה" בניהול כדי לאפשר מסלול קצר',
    'route.customizeHint': 'ניתן להסיר כל תחנה עם ✕ ולהוסיף מקומות נוספים — המסלול יסתגל אוטומטית',
    'route.notInRoute': 'מקומות שלא במסלול',
    'route.notInRouteHint': 'לחץ על "הוסף" כדי לשלב מקום נוסף; המסלול יחושב מחדש אוטומטית',
    'route.addToRoute': 'הוסף',
    'route.resetRoute': 'שחזר מסלול',

    'priority.essential': 'חובה — תחנה מרכזית',
    'priority.recommended': 'מומלץ — תחנה רגילה',
    'priority.extended': 'מורחב — תחנה בונוס',

    'route.note.hoursLabel': 'שעות פעילות:',
    'route.note.hours': 'מומלץ לבקר בשעות היום בלבד (06:00–18:00)',
    'route.note.securityLabel': 'ביטחון:',
    'route.note.security': 'יש להישאר בשטחים המותרים ולציית להנחיות הביטחון המקומיות',
    'route.note.waterLabel': 'מים ושירותים:',
    'route.note.water': 'מומלץ להביא מים ולתכנן הפסקות בישובים עם שירותים',
    'route.note.emergencyLabel': 'טלפון חירום:',
    'route.note.emergency': '100 משטרה, 101 מד"א, 102 כיבוי אש',
    'route.note.weatherLabel': 'מזג אוויר:',
    'route.note.weather': 'בדקו תחזית מזג האוויר לפני היציאה',

    'category.יישוב': 'יישוב',
    'category.אירוע': 'אירוע',
    'category.מקום אחר': 'מקום אחר',
    'category.מיגונית': 'מיגונית',
  },

  en: {
    'app.name': 'Memory 7.10',

    'nav.home': 'Home',
    'nav.map': 'Map',
    'nav.search': 'Search',
    'nav.route': 'Route',
    'nav.admin': 'Admin',
    'nav.login': 'Login',

    'footer.desc': 'An application documenting and commemorating the memorial sites of the October 7, 2023 events, allowing visitors to experience the stories through guided tours.',
    'footer.quickLinks': 'Quick Links',
    'footer.contactLegal': 'Contact & Legal',
    'footer.contact': 'Contact',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.about': 'About',
    'footer.memorial': 'In memory of the victims of October 7, 2023',
    'footer.mapOfSites': 'Sites Map',
    'footer.recommendedRoute': 'Recommended Route',
    'footer.searchLocations': 'Search Locations',

    'location.loading': 'Loading location...',
    'location.errorTitle': 'Error Loading Location',
    'location.notFound': 'Location not found',
    'location.tryAgain': 'Try Again',
    'location.back': 'Back',
    'location.share': 'Share',
    'location.listen': 'Listen to the Story',
    'location.pressToListen': 'Press the button to start listening',
    'location.photos': 'Photos',
    'location.videos': 'Video Clips',
    'location.navigate': 'Navigate to Location',
    'location.navigationOpens': 'Will open your navigation app',
    'location.readMore': 'Read more',
    'location.readLess': 'Show less',
    'location.linkCopied': 'Link copied to clipboard',
    'location.defaultStory': 'A significant memorial site from the October 7 events',
    'location.networkError': 'Network error or server busy. Please try again in a few seconds.',
    'location.loadError': 'Error loading data: ',
    'location.recordingPending': 'Recording Coming Soon',
    'location.recordingPendingDesc': 'The audio story for this location will be added soon',
    'location.shareAudio': 'Share Recording',
    'location.nextStopHeader': 'Continue Your Route',
    'location.nextStopLabel': 'Next Stop:',
    'location.nextStopBtn': 'Next Stop',
    'location.navigateNext': 'Navigate',

    'home.title': 'Walking the Path of Memory',
    'home.subtitle': 'This application guides you on a journey through the massacre sites in the Gaza Envelope, telling the story of each place from that terrible day – October 7, 2023.',
    'home.openMap': 'Open Map',
    'home.startRoute': 'Start Recommended Route',
    'home.howItWorks': 'How Does It Work?',
    'home.step1Title': 'Navigate to a site',
    'home.step1Desc': 'Choose a location on the map or recommended route',
    'home.step2Title': 'Scan the QR code on-site',
    'home.step2Desc': 'To confirm you are at the exact location',
    'home.step3Title': 'Listen to the story',
    'home.step3Desc': 'Accompanied by photos and video clips',
    'home.memorialRouteTitle': 'The Memorial Route',
    'home.memorialRouteDesc': 'Embark on a journey to the main memorial sites in the Gaza region. The recommended route will guide you through the most significant locations of the October 7 events.',
    'home.duration': 'Estimated duration: ~4 hours',
    'home.routePoints': 'stops',
    'home.showOnMap': 'Show Route on Map',
    'home.routeStops': 'Route stops:',
    'home.andMore': 'and more...',
    'home.nearbyTitle': 'Locations Near You',
    'home.recommendedTitle': 'Recommended Locations',
    'home.nearbySubtitle': 'Start your journey from one of these locations',
    'home.openStory': 'Open Location Story',
    'home.viewAll': 'View All Locations',
    'home.defaultStory': 'A significant memorial site from the October 7 events',

    'search.title': 'Search Locations',
    'search.subtitle': 'Search for information about the sites affected on October 7, 2023',
    'search.placeholder': 'Search by location name, description or keywords...',
    'search.filter': 'Filter:',
    'search.sort': 'Sort by:',
    'search.allTypes': 'All Types',
    'search.townPlural': 'Towns',
    'search.militaryPlural': 'Military Bases',
    'search.eventPlural': 'Event Sites',
    'search.otherPlural': 'Other Locations',
    'search.shelterPlural': 'Bomb Shelters',
    'search.sortName': 'Location Name',
    'search.sortViews': 'Most Viewed',
    'search.sortRecent': 'Recently Added',
    'search.loading': 'Loading...',
    'search.foundMany': '{count} locations found',
    'search.foundOne': '1 location found',
    'search.resultsFor': 'Search results for:',
    'search.noResults': 'No results found',
    'search.noResultsHint': 'Try different search terms or remove some filters',
    'search.clearSearch': 'Clear Search',
    'search.discoverMore': 'Discover More',
    'search.showOnMap': 'Map',
    'search.audio': 'Audio',
    'search.errorTitle': 'Error Loading Data',
    'search.cannotLoad': 'Unable to load data',
    'search.tryLater': 'An error occurred loading the locations list. Please try again later.',
    'search.tryAgain': 'Try Again',
    'search.retrying': 'Retrying... attempt {n}/2',

    'route.title': 'Recommended Route',
    'route.stops': 'stops',
    'route.duration': 'Est. duration:',
    'route.hours': 'hours',
    'route.totalDistance': 'Total distance:',
    'route.km': 'km',
    'route.startNavigation': 'Start Navigation',
    'route.navigateTo': 'Navigate',
    'route.moreInfo': 'More Info',
    'route.recommendedTime': 'Recommended time:',
    'route.minutes': 'min',
    'route.prevDistance': 'Distance from previous stop:',
    'route.driveTime': 'Drive time:',
    'route.defaultStory': 'A significant memorial site from the October 7, 2023 events',
    'route.mapTitle': 'Route Map',
    'route.mapLocations': 'Locations Map',
    'route.clickForInfo': 'Click on stops for more information',
    'route.stopsTitle': 'Route Stops',
    'route.stop': 'Stop',
    'route.importantNotes': 'Important Notes for Visitors',
    'route.shareLocationBtn': 'Share Location',
    'route.adjustToMyLocation': 'Adjust to My Location',
    'route.startRouteBtn': 'Start Route',
    'route.viewMap': 'View Map',
    'route.inGazaEnvelope': 'You are in the Gaza Envelope area. The route has been personalized for your location.',
    'route.fromSderot': 'The route is optimally built from Sderot in a logical visiting order.',
    'route.loadingLocations': 'Loading locations...',
    'route.locatingPosition': 'Locating...',
    'route.locating': 'Locating...',
    'route.shareYourLocation': 'Share Your Location',
    'route.shareLocationDesc': 'To create a personalized route, we need access to your location to suggest the best route for you',
    'route.orStartFromSderot': 'Or start with a general route from Sderot',
    'route.mapSubtitleRoute': 'Click on stops for more information',
    'route.mapSubtitleSderot': 'Route starts from Sderot in a logical visiting order',
    'route.mapSubtitleShare': 'Share your location to get a personalized route',
    'route.markVisited': 'Mark as Visited',
    'route.visited': 'Visited',
    'route.mode.label': 'Choose route:',
    'route.mode.essential': 'Short',
    'route.mode.essentialDesc': 'Must-see stops only',
    'route.mode.recommended': 'Recommended',
    'route.mode.recommendedDesc': 'Main stops',
    'route.mode.full': 'Full',
    'route.mode.fullDesc': 'All stops',
    'route.mode.custom': 'By Time',
    'route.mode.budgetLabel': 'Time budget:',
    'route.mode.hours': 'hours',
    'route.mode.noPriorityHint': 'Tip: Mark locations as "essential" in admin to enable short routes',
    'route.customizeHint': 'You can remove any stop with ✕ and add more locations — the route adjusts automatically',
    'route.notInRoute': 'Locations not in route',
    'route.notInRouteHint': 'Click "Add" to include a location; the route will recalculate automatically',
    'route.addToRoute': 'Add',
    'route.resetRoute': 'Reset route',

    'priority.essential': 'Essential — main stop',
    'priority.recommended': 'Recommended — regular stop',
    'priority.extended': 'Extended — bonus stop',

    'route.note.hoursLabel': 'Hours:',
    'route.note.hours': 'Recommended visiting hours are daytime only (06:00–18:00)',
    'route.note.securityLabel': 'Security:',
    'route.note.security': 'Stay in permitted areas and follow local security instructions',
    'route.note.waterLabel': 'Water & Facilities:',
    'route.note.water': 'Bring water and plan breaks at locations with facilities',
    'route.note.emergencyLabel': 'Emergency Numbers:',
    'route.note.emergency': '100 Police, 101 Ambulance, 102 Fire Department',
    'route.note.weatherLabel': 'Weather:',
    'route.note.weather': 'Check the weather forecast before your visit',

    'category.יישוב': 'Town',
    'category.אירוע': 'Event Site',
    'category.מקום אחר': 'Other Site',
    'category.מיגונית': 'Bomb Shelter',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return stored === 'en' ? 'en' : 'he';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.dir = lang === 'he' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  }, [lang]);

  const t = (key) => translations[lang]?.[key] ?? translations.he[key] ?? key;
  const toggleLang = () => setLang(l => (l === 'he' ? 'en' : 'he'));
  const isRTL = lang === 'he';

  // Resolve display name/story for a location object based on current language
  const locName = (loc) => (lang === 'en' && loc?.name_en) ? loc.name_en : loc?.name;
  const locStoryTitle = (loc) => (lang === 'en' && loc?.full_story_en?.title) ? loc.full_story_en.title : loc?.full_story?.title;
  const locStoryContent = (loc) => (lang === 'en' && loc?.full_story_en?.content) ? loc.full_story_en.content : loc?.full_story?.content;

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t, isRTL, locName, locStoryTitle, locStoryContent }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
